/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_machinebrain_free: (a: number, b: number) => void;
export const machinebrain_add_axis: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const machinebrain_add_channel: (a: number, b: number, c: any) => void;
export const machinebrain_add_work_offset: (a: number, b: number, c: number) => number;
export const machinebrain_clear_config: (a: number) => void;
export const machinebrain_get_full_state: (a: number) => any;
export const machinebrain_home_all: (a: number) => void;
export const machinebrain_home_all_ordered: (a: number, b: number, c: number, d: number) => void;
export const machinebrain_home_axis: (a: number, b: number) => void;
export const machinebrain_jog_axis: (a: number, b: number, c: number) => void;
export const machinebrain_jog_axis_feed: (a: number, b: number, c: number, d: number) => void;
export const machinebrain_jog_axis_rapid: (a: number, b: number, c: number) => void;
export const machinebrain_jump_blocks: (a: number, b: number, c: number) => void;
export const machinebrain_load_program: (a: number, b: number, c: number, d: number) => void;
export const machinebrain_move_to: (a: number, b: number, c: number) => void;
export const machinebrain_new: () => number;
export const machinebrain_reset_program: (a: number, b: number) => void;
export const machinebrain_set_active_tool: (a: number, b: number, c: number) => void;
export const machinebrain_set_active_wcs: (a: number, b: number) => void;
export const machinebrain_set_axis_accel: (a: number, b: number, c: number) => void;
export const machinebrain_set_axis_invert: (a: number, b: number, c: number) => void;
export const machinebrain_set_axis_machine_zero: (a: number, b: number, c: number) => void;
export const machinebrain_set_cutter_comp: (a: number, b: number, c: number) => void;
export const machinebrain_set_estop: (a: number, b: number) => void;
export const machinebrain_set_feed_override: (a: number, b: number, c: number) => void;
export const machinebrain_set_single_block: (a: number, b: number, c: number) => void;
export const machinebrain_set_tool_length: (a: number, b: number, c: number) => void;
export const machinebrain_set_tool_length_comp: (a: number, b: number, c: number) => void;
export const machinebrain_set_tool_radius: (a: number, b: number, c: number) => void;
export const machinebrain_set_tool_table_entry: (a: number, b: number, c: number, d: number, e: number) => void;
export const machinebrain_set_work_zero: (a: number, b: number, c: number, d: number) => void;
export const machinebrain_step_once: (a: number, b: number) => void;
export const machinebrain_tick: (a: number, b: number) => void;
export const machinebrain_toggle_pause: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
